name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the commit number
        run: |
          tag=$(git rev-list --count HEAD)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Check Docker username
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push main-app
        run: |
          docker build -t username/main-app:tag .
          docker push username/main-app:tag
#
#      - name: Build and push post-app
#        working-directory: ./post_app
#        run: |
#          docker build -t username/post-app:tag .
#          docker push username/post-app:tag

