name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get the commit number
        run: |
          commit_count=$(git rev-list --count HEAD) # export tag="v${commit_count}"
          echo "Commit count: $commit_count"
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          

      - name: Build and push python-main-app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/CI-Cd-main:v${{ env.COMMIT_COUNT}} .
          docker push ${{ secrets.DOCKER_USERNAME }}/CI-Cd-main:v${{ env.COMMIT_COUNT}}

      - name: Build and push Post-app
        working-directory: ./post_app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/post-app:v${{ env.COMMIT_COUNT}} .
          docker push ${{ secrets.DOCKER_USERNAME }}/post-app:v${{ env.COMMIT_COUNT}}

      - name: Build and push Music-app
        working-directory: ./music_app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/music-app:v${{ env.COMMIT_COUNT}} .
          docker push ${{ secrets.DOCKER_USERNAME }}/music-app:v${{ env.COMMIT_COUNT}}

      - name: Build and push Document-app
        working-directory: ./document_app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/document-app:v${{ env.COMMIT_COUNT}} .
          docker push ${{ secrets.DOCKER_USERNAME }}/document-app:v${{ env.COMMIT_COUNT}}




